"""Short labels and media metadata. Edit prose in content/zh and content/en."""

PROFILE = {'name': 'Sihao Chen',
 'handle': 'mijinmo',
 'github': 'https://github.com/mijinmo',
 'email': 'paul.mijinmo@gmail.com'}

CATEGORIES = {'commercial': ('商业项目', 'Commercial work'),
 'indie': ('独立游戏', 'Independent games'),
 'experimental': ('原型与实验', 'Prototypes & experiments')}

PROJECTS = [{'id': 'arknights',
  'category': 'commercial',
  'title': ('明日方舟', 'Arknights'),
  'date': ('2025 年 7 月 — 至今', 'Jul 2025 — Present'),
  'image': 'images/arknights_logo.jpg',
  'url': ('https://zh.wikipedia.org/wiki/明日方舟', 'https://en.wikipedia.org/wiki/Arknights'),
  'platform': ('维基百科', 'Wikipedia'),
  'archived': False},
 {'id': 'kwyjibo',
  'category': 'indie',
  'title': ('Kwyjibo Adventure', 'Kwyjibo Adventure'),
  'date': ('2025 年初 · 毕业项目', 'Early 2025 · Capstone project'),
  'image': 'images/kwyjibo-header.jpg',
  'url': 'https://store.steampowered.com/app/3603820/Kwyjibo_Adventure/',
  'platform': ('Steam 商店', 'View on Steam'),
  'archived': True},
 {'id': 'exp10sion',
  'category': 'indie',
  'title': ('Exp10sion', 'Exp10sion'),
  'date': ('2022 年 · 起源于 Ludum Dare 51', '2022 · Began at Ludum Dare 51'),
  'image': 'images/g1.png',
  'url': 'https://store.steampowered.com/app/2618850/Exp10sion/',
  'platform': ('Steam 商店', 'View on Steam'),
  'archived': True},
 {'id': 'sleep',
  'category': 'indie',
  'title': ('快睡觉！', 'Sleep!'),
  'date': ('2024 年 5 月', 'May 2024'),
  'image': 'images/sleepStaticBanner.jpg',
  'url': 'https://xiu0922koway.itch.io/sleep-demo',
  'platform': ('itch.io 页面', 'View on itch.io'),
  'archived': True},
 {'id': 'penny',
  'category': 'indie',
  'title': ('Penny the Memory Mender', 'Penny the Memory Mender'),
  'date': ('2023 年 12 月', 'Dec 2023'),
  'image': 'images/Penny.jpg',
  'url': 'https://l-mop.itch.io/moon-witch',
  'platform': ('itch.io 页面', 'View on itch.io'),
  'archived': True},
 {'id': 'golden-retriever',
  'category': 'indie',
  'title': ('金色回归', 'Golden Retriever'),
  'date': ('2023 年 6 月', 'Jun 2023'),
  'image': 'images/g5.png',
  'url': 'https://cortexa233.itch.io/golden-retriever',
  'platform': ('itch.io 页面', 'View on itch.io'),
  'archived': True},
 {'id': 'bad-bad-roots',
  'category': 'indie',
  'title': ('Bad Bad Roots', 'Bad Bad Roots'),
  'date': ('2023 年 2 月 · GGJ', 'Feb 2023 · GGJ'),
  'image': 'images/g4.png',
  'url': 'https://psa1ms77.itch.io/bad-bad-roots',
  'platform': ('itch.io 页面', 'View on itch.io'),
  'archived': True},
 {'id': 'detective',
  'category': 'indie',
  'title': ('So a Detective Walks into a Bar…', 'So a Detective Walks into a Bar…'),
  'date': ('2022 年 9 月 · Mini Jam', 'Sep 2022 · Mini Jam'),
  'image': 'images/g2.png',
  'url': 'https://psa1ms77.itch.io/so-a-detective-walks-into-a-bar',
  'platform': ('itch.io 页面', 'View on itch.io'),
  'archived': True},
 {'id': 'giggle',
  'category': 'indie',
  'title': ('Giggle is a Ladder', 'Giggle is a Ladder'),
  'date': ('2022 年 8 月', 'Aug 2022'),
  'image': 'images/g3.jpg',
  'url': 'https://xiu0922koway.itch.io/giggle-is-a-ladder',
  'platform': ('itch.io 页面', 'View on itch.io'),
  'archived': True},
 {'id': 'breeze',
  'category': 'experimental',
  'title': ('Breeze', 'Breeze'),
  'date': ('2024 年', '2024'),
  'image': 'images/Screenshot_Breeze.png',
  'url': '',
  'platform': ('项目页面', 'Project page'),
  'archived': True},
 {'id': 'balance',
  'category': 'experimental',
  'title': ('体感醉酒平衡游戏', 'Drunkard Balancing Game'),
  'date': ('2024 年 1 月', 'Jan 2024'),
  'image': '',
  'url': 'Files/IMG_5372.MOV',
  'platform': ('下载演示视频', 'Download demonstration'),
  'archived': True},
 {'id': 'metroidvania',
  'category': 'experimental',
  'title': ('银河城关卡设计原型', 'Metroidvania Level Prototype'),
  'date': ('2024 年 1 月', 'Jan 2024'),
  'image': 'images/metroid.png',
  'url': 'https://psa1ms77.itch.io/metroidvaniatestout',
  'platform': ('itch.io 页面', 'View on itch.io'),
  'archived': True},
 {'id': 'cs-map',
  'category': 'experimental',
  'title': ('CS 社区地图', 'CS Community Map'),
  'date': ('学生时期项目', 'Student project'),
  'image': 'images/csmap.jpg',
  'url': 'https://steamcommunity.com/sharedfiles/filedetails/?id=3180079185',
  'platform': ('Steam 创意工坊', 'Steam Workshop'),
  'archived': True},
 {'id': 'scented-days',
  'category': 'experimental',
  'title': ('Scented Days', 'Scented Days'),
  'date': ('2024 年', '2024'),
  'image': 'images/SmellGame.png',
  'url': 'research.html#scented-days',
  'platform': ('论文与项目资料', 'Paper & project resources'),
  'archived': True}]

RESEARCH = [{'id': 'lpfc',
  'date': ('2021 年 7 月 — 2022 年 5 月', 'Jul 2021 — May 2022'),
  'image': 'images/n1.PNG',
  'title': ('工作记忆任务中 LPFC 神经群体的错误试次响应', 'LPFC Population Responses in Working Memory Error Trials')},
 {'id': 'larvae',
  'date': ('2019 年 6 月 — 2022 年 6 月', 'Jun 2019 — Jun 2022'),
  'image': 'images/n2.jpg',
  'title': ('果蝇幼虫运动视觉的神经回路', 'Neural Circuits Underlying Motion Vision in Drosophila Larvae'),
  'url': 'https://www.kaggle.com/datasets/hongbing/drosophila-larva-motion'},
 {'id': 'prl1',
  'date': ('2019 年 6 月 — 2022 年 6 月', 'Jun 2019 — Jun 2022'),
  'image': 'images/n3.PNG',
  'title': ('PRL-1 突变果蝇翅膀上举表型的神经机制', 'Neural Control of the Wing Held-up Phenotype in PRL-1 Mutant Flies')},
 {'id': 'fmri',
  'date': ('2021 年 11 月 · 课程项目', 'Nov 2021 · Course project'),
  'image': 'images/c2.PNG',
  'title': ('全脑 fMRI 分析与图片情绪效价预测', 'Whole-brain fMRI Analysis & Picture Valence Prediction')},
 {'id': 'retina',
  'date': ('2021 年 11 月 · 课程项目', 'Nov 2021 · Course project'),
  'image': 'images/c1.PNG',
  'title': ('视网膜图像分析', 'Retinal Scan Image Analysis')}]

PIXEL_ART = ['p1.png',
 'p2.png',
 'p8.png',
 'p4.png',
 'character design1.png',
 'p5.gif',
 'p6.png',
 'p7.png',
 'p3.gif',
 'Character_animation.gif',
 'bacon.png',
 'heros.png']

PHOTOGRAPHY = ['ph9.JPG', 'ph2.JPG', 'ph3.JPG', 'ph4.JPG', 'ph5.JPG', 'ph6.JPG', 'ph7.JPG', 'ph8.JPG', 'ph10.JPG']

SOURCES = {'kwyjibo': 'https://store.steampowered.com/api/appdetails?appids=3603820&l=english',
 'kwyjibo_checked': '2026-09-06',
 'kwyjibo_artwork': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3603820/25ea65013ad4754f6314d356c172a70c658fbb77/header.jpg?t=1744067676',
 'scented_days': 'https://dl.acm.org/doi/10.1145/3665463.3678844'}

