"""Build a dependency-free, bilingual static portfolio for GitHub Pages."""
from pathlib import Path
from html import escape
from urllib.parse import quote
import struct
import sys
from prose import render as render_markdown, plain as plain_markdown

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'site'))
from content import PROFILE, PROJECTS, CATEGORIES, RESEARCH, PIXEL_ART, PHOTOGRAPHY

PAGES = ['index.html', 'projects.html', 'research.html', 'art.html', 'about.html', 'Journey_Cam_Analysis.html']
NAV = [('首页', 'Home'), ('作品', 'Projects'), ('文章与研究', 'Writing & research'), ('美术', 'Art'), ('关于', 'About')]
LANG = 'zh'

def md(key):
    return render_markdown(ROOT, LANG, key)

def t(pair):
    return pair[0 if LANG == 'zh' else 1] if isinstance(pair, (tuple, list)) else pair

def e(value):
    return escape(str(value), quote=True)

def asset(path):
    return ('../' if LANG == 'en' else '') + quote(path, safe='/')

def image_size(path):
    """Read dimensions without a third-party image dependency."""
    with (ROOT / path).open('rb') as f:
        head = f.read(24)
        if head.startswith(b'\x89PNG'):
            return struct.unpack('>II', head[16:24])
        if head.startswith(b'GIF'):
            return struct.unpack('<HH', head[6:10])
        if head.startswith(b'RIFF') and head[8:12] == b'WEBP':
            f.seek(0)
            data = f.read(32)
            if data[12:16] == b'VP8 ':
                width, height = struct.unpack('<HH', data[26:30])
                return width & 0x3fff, height & 0x3fff
            if data[12:16] == b'VP8X':
                return int.from_bytes(data[24:27], 'little') + 1, int.from_bytes(data[27:30], 'little') + 1
            if data[12:16] == b'VP8L':
                bits = int.from_bytes(data[21:25], 'little')
                return (bits & 0x3fff) + 1, ((bits >> 14) & 0x3fff) + 1
        if head.startswith(b'\xff\xd8'):
            f.seek(2)
            while True:
                byte = f.read(1)
                if not byte:
                    break
                if byte != b'\xff':
                    continue
                marker = f.read(1)
                while marker == b'\xff':
                    marker = f.read(1)
                if marker in (b'\xd8', b'\xd9'):
                    continue
                length = struct.unpack('>H', f.read(2))[0]
                if marker[0] in (0xC0, 0xC1, 0xC2, 0xC3):
                    _, height, width = struct.unpack('>BHH', f.read(5))
                    return width, height
                f.seek(length - 2, 1)
    raise ValueError(f'Unsupported image: {path}')

def img(path, alt, eager=False, css=''):
    width, height = image_size(path)
    return f'<img src="{asset(path)}" alt="{e(alt)}" width="{width}" height="{height}" loading="{"eager" if eager else "lazy"}" decoding="async" class="{css}">'

def link(url, label, css='text-link'):
    url = t(url)
    if url.startswith(('Files/', 'images/')):
        url = asset(url)
    return f'<a class="{css}" href="{e(url)}">{e(t(label))}</a>'

def section_heading(number, title, extra=''):
    return f'<div class="section-heading"><h2>{e(t(title))}</h2></div>'

def heading(title, content_key):
    return f'<header class="page-heading major"><h1>{e(t(title))}</h1>{md(content_key)}</header>'

def shell(page, body):
    i = PAGES.index(page)
    title = t(NAV[i]) if i < 5 else t(('《风之旅人》的镜头设计', 'Camera Design in Journey'))
    other = ('en/' if LANG == 'zh' else '../') + page
    zh = ('../' if LANG == 'en' else '') + page
    en = ('en/' if LANG == 'zh' else '') + page
    nav = ''.join(f'<li class="{"active" if p == page or (page == PAGES[5] and p == PAGES[2]) else ""}"><a href="{p}" {"aria-current=\"page\"" if p == page or (page == PAGES[5] and p == PAGES[2]) else ""}>{e(t(label))}</a></li>' for p, label in zip(PAGES, NAV))
    description = plain_markdown(ROOT, LANG, 'pages/site-description')
    intro = ''
    if page == 'index.html':
        intro = f'''<div id="intro"><h1>Sihao Chen</h1>{md('pages/home-intro')}<ul class="actions"><li><a href="#main" class="button icon solid solo fa-arrow-down scrolly">{t(('查看作品', 'View projects'))}</a></li></ul></div>'''
    scripts = ''.join(f'<script src="{asset("assets/js/" + name)}"></script>' for name in ['jquery.min.js', 'jquery.scrollex.min.js', 'jquery.scrolly.min.js', 'browser.min.js', 'breakpoints.min.js', 'util.js', 'main.js', 'portfolio.js'])
    return f'''<!doctype html>
<!-- Generated by scripts/build.py. Edit content/ Markdown for prose. -->
<!-- Massively by HTML5 UP · html5up.net · CCA 3.0 license -->
<html lang="{'zh-CN' if LANG == 'zh' else 'en'}">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>{e(title)} — Sihao Chen / mijinmo</title>
<meta name="description" content="{e(description)}"><meta name="theme-color" content="#212931">
<link rel="alternate" hreflang="zh-CN" href="{zh}"><link rel="alternate" hreflang="en" href="{en}"><link rel="alternate" hreflang="x-default" href="{zh}">
<link rel="stylesheet" href="{asset('assets/css/main.css')}">
<link rel="stylesheet" href="{asset('assets/css/content.css')}">
<noscript><style>#nav{{display:flex;height:auto}}#nav ul.links{{flex-wrap:wrap}}#wrapper{{background:#212931}}#wrapper.fade-in:before{{display:none}}</style></noscript>
</head><body>
<a class="skip-link" href="#main">{t(('跳至正文', 'Skip to content'))}</a>
<div id="wrapper" class="fade-in">{intro}
<header id="header"><a href="index.html" class="logo">Sihao Chen</a></header>
<nav id="nav" aria-label="{t(('主导航', 'Main navigation'))}"><ul class="links">{nav}<li><a href="{other}" lang="{'en' if LANG == 'zh' else 'zh-CN'}" hreflang="{'en' if LANG == 'zh' else 'zh-CN'}" aria-label="{t(('Switch to English', '切换为中文'))}">{t(('English', '中文'))}</a></li></ul><ul class="icons"><li><a href="{PROFILE['github']}" class="icon brands fa-github"><span class="label">GitHub</span></a></li></ul></nav>
<main id="main">{body}</main>
<footer id="footer"><section class="split contact"><section><h3>{t(('邮箱', 'Email'))}</h3><p>{link('mailto:' + PROFILE['email'], PROFILE['email'])}</p></section><section><h3>GitHub</h3><p>{link(PROFILE['github'], 'mijinmo')}</p></section></section></footer>
<div id="copyright"><ul><li>© Sihao Chen / mijinmo</li><li>Design: <a href="https://html5up.net">HTML5 UP</a></li></ul></div></div>{scripts}
</body></html>'''

def career():
    p = PROJECTS[0]
    return f'''<article class="career" id="arknights"><header><span class="date">{e(t(p['date']))}</span><h2>{e(t(p['title']))}</h2></header><div class="career-logo image fit">{img(p['image'], t(('明日方舟公开标识', 'Arknights public logo')), eager=True)}</div>
{md('projects/' + p['id'])}<ul class="actions special"><li>{link(p['url'], p['platform'], 'button')}</li></ul></article>'''

def card(p, featured=False):
    title = t(p['title'])
    if p['image']:
        media = img(p['image'], t((title + ' · 项目画面', title + ' — project image')))
    else:
        media = f'<div class="controller-art" aria-hidden="true"><span>↔</span><span>MICRO:BIT × UNITY</span></div>'
    destination = t(p['url'])
    if destination:
        media = f'<a class="project-image" href="{e(asset(destination) if destination.startswith("Files/") else destination)}" aria-label="{e(title)}">{media}</a>'
    else:
        media = f'<div class="project-image">{media}</div>'
    archive = f'<span class="archive-tag">{t(("学生作品 · 已停止维护", "Student work · No longer maintained"))}</span>' if p['archived'] else ''
    video = f'<details class="video-details"><summary>{t(("观看演示视频", "Watch demonstration"))}</summary><video controls preload="none" playsinline width="640" height="480" aria-label="{e(title)}"><source src="{asset("Files/IMG_5372.MOV")}">{t(("浏览器无法播放时，请下载视频。", "If playback is unsupported, download the video."))}</video></details>' if p['id'] == 'balance' else ''
    return f'''<article class="project-card" id="{p['id']}" data-category="{p['category']}"><header><span class="date">{e(t(p['date']))}</span><h2>{e(title)}</h2></header>{media}
<div class="project-copy">{md('projects/' + p['id'])}{video}<div class="project-end">{link(p['url'], p['platform'], 'button') if p['url'] else ''}<p>{archive}</p></div></div></article>'''

def home():
    return f'''<section class="section">{career()}</section><section class="section" id="selected">{section_heading('', ('独立游戏', 'Independent games'))}<div class="project-grid">{''.join(card(p) for p in PROJECTS[1:3])}</div></section><section><ul class="actions special"><li>{link('projects.html', ('查看全部作品', 'All projects'), 'button')}</li></ul></section>'''

def projects():
    filters = '<div class="filters" hidden role="group" aria-label="' + t(('按类别筛选作品', 'Filter projects by category')) + '">'
    for key, name in [('all', ('全部', 'All'))] + list(CATEGORIES.items()):
        filters += f'<button type="button" data-filter="{key}" aria-pressed="{"true" if key == "all" else "false"}">{e(t(name))}</button>'
    filters += f'</div><p class="filter-status" role="status" aria-live="polite" data-template="{t(("显示 {count} 个项目", "Showing {count} projects"))}" hidden></p>'
    groups = ''
    for n, (key, label) in enumerate(CATEGORIES.items(), 1):
        items = [p for p in PROJECTS if p['category'] == key]
        body = career() if key == 'commercial' else '<div class="project-grid">' + ''.join(card(p) for p in items) + '</div>'
        groups += f'<section class="project-group section" id="{key}" data-group="{key}">{section_heading(f"0{n}", label)}{body}</section>'
    return heading(('作品索引', 'PROJECT INDEX'), 'pages/projects-intro') + filters + groups

def research():
    body = heading(('文章与研究', 'WRITING & RESEARCH'), 'pages/research-intro')
    body += f'<section class="section">{section_heading("01", ("游戏设计笔记", "Game design notes"))}<article class="editorial-card"><a href="Journey_Cam_Analysis.html">{img("images/Journey_Blog_screenshot.png", t(("风之旅人镜头分析配图", "Journey camera analysis illustration")))}</a><div><p class="eyebrow">{t(("2023 年 10 月 15 日 · 设计分析", "OCT 15, 2023 · DESIGN ANALYSIS"))}</p><h3>{t(("《风之旅人》的镜头设计", "Camera Design in Journey"))}</h3>{md("pages/journey-summary")}{link("Journey_Cam_Analysis.html", ("阅读全文", "Read the article"))}</div></article></section>'
    p = PROJECTS[-1]
    body += f'''<section class="section" id="scented-days">{section_heading('02', ('交互研究与发表', 'Interaction research & publication'))}
<article class="publication"><div>{img(p['image'], 'Scented Days')}{img('images/SmellGameFigure.png', t(('Scented Days 气味交互装置', 'Scented Days scent interaction apparatus')))}</div><div><p class="eyebrow">CHI PLAY 2024</p><h3>Scented Days: Exploring the Capacity of Smell Narratives</h3>{md('projects/scented-days')}<p class="archive-tag">{t(('学生作品 · 已停止维护', 'Student work · No longer maintained'))}</p><div class="resource-links">{link('https://dl.acm.org/doi/10.1145/3665463.3678844', ('阅读正式论文（ACM）', 'Read the published paper (ACM)'))}{link('Files/Final_DIS_Scent_Days_Paper-4.pdf', ('早期稿件 PDF', 'Earlier manuscript (PDF)'))}{link('https://drive.google.com/file/d/185Kk26mrY-QpZoe5uvT0gKt4rDbM3biv/view?usp=sharing', ('下载游戏', 'Download game'))}</div></div></article></section>'''
    body += f'<section class="section" id="neuroscience">{section_heading("03", ("神经科学与课程研究", "Neuroscience & coursework"))}<div class="section-description">{md("pages/research-archive-note")}</div><div class="research-list">'
    for p in RESEARCH:
        body += f'<article class="research-item" id="{p["id"]}">{img(p["image"], t(p["title"]))}<div><p class="eyebrow">{e(t(p["date"]))}</p><h3>{e(t(p["title"]))}</h3>{md("research/" + p["id"])}{link(p["url"], ("查看数据集", "View dataset")) if p.get("url") else ""}</div></article>'
    return body + '</div></section>'

def art():
    body = heading(('美术与摄影', 'ART & PHOTOGRAPHY'), 'pages/art-intro')
    for n, (files, label, cls) in enumerate([(PIXEL_ART, ('像素美术', 'Pixel art'), 'pixel'), (PHOTOGRAPHY, ('胶片摄影', 'Film photography'), 'photo')], 1):
        body += f'<section class="section">{section_heading(f"0{n}", label)}<div class="gallery {cls}">'
        for i, filename in enumerate(files, 1):
            name = t(label) + f' {i:02d}'
            path = 'images/' + filename
            body += f'<figure><a href="{asset(path)}" aria-label="{e(t(("查看原图：", "View original: ")) + name)}">{img(path, name)}</a><figcaption>{e(name)}</figcaption></figure>'
        body += '</div></section>'
    return body + '<p class="section-description">' + link('https://www.flickr.com/photos/197007325@N03', ('在 Flickr 上查看更多摄影', 'More photography on Flickr')) + '</p>'

def about():
    return heading(('关于我', 'ABOUT'), 'pages/about-intro') + f'''
<div class="about-layout"><section class="prose">{md('pages/about')}
<div class="resource-links">{link(PROFILE['github'], 'GitHub / mijinmo')}{link('https://psa1ms77.itch.io/', 'itch.io / Psalms77')}{link('https://www.gcores.com/users/224023/talks', ('机核主页', 'Gamecores profile'))}{link('https://discord.gg/YScvC67Dwb', 'Discord')}</div></section>
<aside class="timeline">{md('pages/about-timeline')}</aside></div>'''

def journey():
    return heading(('《风之旅人》的镜头设计', 'Navigating the Visuals of Journey'), 'pages/journey-intro') + f'<article class="article-body">{img("images/Journey_Blog_screenshot.png", t(("风之旅人镜头分析配图", "Journey camera analysis illustration")), eager=True)}<div class="article-tools">{link("Files/Journey_Camera_System_remake.zip", ("下载镜头复现 Demo（Unity）", "Download camera recreation (Unity)"))}</div><div class="prose">{md("articles/journey")}</div><div class="project-note">{md("pages/journey-archive-note")}</div>{link("research.html", ("返回文章与研究", "Back to writing & research"))}</article>'

def write(path, content):
    target = ROOT / path
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary = target.with_suffix('.html.tmp')
    temporary.write_text(content + '\n', encoding='utf-8', newline='\n')
    temporary.replace(target)

def build():
    global LANG
    output = {}
    for LANG in ('zh', 'en'):
        for page, render in zip(PAGES, [home, projects, research, art, about, journey]):
            output[('en/' if LANG == 'en' else '') + page] = shell(page, render())
    redirects = {'index_cn.html': 'index.html', 'index_2.html': 'projects.html',
                 'publicans.html': 'research.html#scented-days', 'Blogs.html': 'research.html',
                 'neuroscience.html': 'research.html#neuroscience', 'course_project.html': 'research.html#fmri',
                 'alt_games.html': 'projects.html#experimental', 'ref.html': 'index.html', 'blog8.html': 'Journey_Cam_Analysis.html'}
    for old, target in redirects.items():
        output[old] = f'<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="refresh" content="0;url={target}"><title>页面已迁移 — Sihao Chen</title></head><body><p>页面已整理至新位置。<a href="{target}">继续浏览 / Continue</a></p></body></html>'
    for path, html in output.items():
        write(path, html)
    print(f'Built {len(PAGES) * 2} content pages and {len(redirects)} legacy redirects.')

if __name__ == '__main__':
    build()
