"""Validate generated output, content invariants, and GitHub Pages links."""
from pathlib import Path
from html.parser import HTMLParser
from urllib.parse import urlsplit, unquote
import hashlib
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'site'))
from content import PROJECTS, RESEARCH, PIXEL_ART, PHOTOGRAPHY
from prose import render

VOID = {'area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input', 'link', 'meta', 'param', 'source', 'track', 'wbr'}
class Document(HTMLParser):
    def __init__(self, path):
        super().__init__(convert_charrefs=True)
        self.path = path
        self.ids = set()
        self.links = []
        self.stack = []
        self.h1 = 0
        self.lang = None
        self.alternates = {}
        self.images = 0
        self.feed(path.read_text(encoding='utf-8'))
        assert not self.stack, f'{path}: unclosed elements {self.stack}'

    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        if tag not in VOID:
            self.stack.append(tag)
        if 'id' in a:
            assert a['id'] not in self.ids, f'{self.path}: duplicate id {a["id"]}'
            self.ids.add(a['id'])
        if tag == 'html':
            self.lang = a.get('lang')
        if tag == 'h1':
            self.h1 += 1
        if tag == 'link' and a.get('rel') == 'alternate':
            self.alternates[a.get('hreflang')] = a.get('href')
        if tag == 'img':
            self.images += 1
            assert a.get('alt'), f'{self.path}: missing alt'
            assert int(a.get('width', 0)) > 0 and int(a.get('height', 0)) > 0, f'{self.path}: missing image dimensions'
            assert a.get('loading') in ('eager', 'lazy'), f'{self.path}: missing image loading policy'
        if tag == 'video':
            assert 'autoplay' not in a and a.get('preload') == 'none', f'{self.path}: video preloads or autoplays'
        for attr in ('href', 'src'):
            if attr in a:
                assert a[attr] not in ('', '#'), f'{self.path}: empty {attr}'
                self.links.append(a[attr])

    def handle_endtag(self, tag):
        if tag in VOID:
            return
        assert self.stack and self.stack[-1] == tag, f'{self.path}: unexpected closing {tag}; stack {self.stack}'
        self.stack.pop()

def main():
    files = list(ROOT.glob('*.html')) + list((ROOT / 'en').glob('*.html'))
    docs = {p.resolve(): Document(p) for p in files}
    internal = 0
    for path, doc in docs.items():
        source = path.read_text(encoding='utf-8')
        for bad in ('github.com/Psalms77', 'prts.wiki', 'beilunmoni.png', 'jiaomie.png', 'Vulpisfoglia', 'Contrail', '408-646', '150-8891', 'schen455@', 'pc4499520@', 'user-scalable=no'):
            assert bad not in source, f'{path}: stale/private content {bad}'
        if 'Generated by scripts/build.py' in source:
            assert doc.h1 == 1, f'{path}: expected one h1'
            expected_lang = 'en' if path.parent.name == 'en' else 'zh-CN'
            assert doc.lang == expected_lang, f'{path}: wrong language'
            assert set(doc.alternates) == {'en', 'zh-CN', 'x-default'}
            for language, href in doc.alternates.items():
                target = (path.parent / href).resolve()
                assert docs[target].lang == ('zh-CN' if language == 'x-default' else language)
                assert target.name == path.name
        for href in doc.links:
            parsed = urlsplit(href)
            if parsed.scheme or parsed.netloc:
                continue
            assert not parsed.path.startswith('/'), f'{path}: root-relative link breaks project hosting: {href}'
            target = (path.parent / unquote(parsed.path)).resolve() if parsed.path else path
            assert target.is_relative_to(ROOT) and target.exists(), f'{path}: missing target {href}'
            # Enforce filename case even on Windows: Pages runs on a case-sensitive filesystem.
            if target != ROOT:
                assert target.name in [p.name for p in target.parent.iterdir()], f'{path}: filename case mismatch {href}'
            if parsed.fragment and target in docs:
                assert unquote(parsed.fragment) in docs[target].ids, f'{path}: broken fragment {href}'
            if path.parent.name == 'en' and target in docs and parsed.path and not href.startswith('../'):
                assert target.parent.name == 'en', f'{path}: navigation lost English language'
            internal += 1
    ids = {p['id'] for p in PROJECTS}
    assert len(ids) == len(PROJECTS) == 14
    for prefix in ('', 'en/'):
        project_doc = docs[(ROOT / prefix / 'projects.html').resolve()]
        assert ids <= project_doc.ids, f'{prefix}: missing project'
        home = docs[(ROOT / prefix / 'index.html').resolve()]
        assert ids & home.ids == {'arknights', 'kwyjibo', 'exp10sion'}, 'Unexpected home selection'
        research = docs[(ROOT / prefix / 'research.html').resolve()]
        assert {p['id'] for p in RESEARCH} <= research.ids
        art = docs[(ROOT / prefix / 'art.html').resolve()]
        assert art.images == len(PIXEL_ART) + len(PHOTOGRAPHY) == 21
    assert '2025 年 7 月' in (ROOT / 'index.html').read_text(encoding='utf-8')
    assert 'Producer' in (ROOT / 'index.html').read_text(encoding='utf-8')
    original = render(ROOT, 'en', 'articles/journey')
    assert original in (ROOT / 'en/Journey_Cam_Analysis.html').read_text(encoding='utf-8'), 'English article was not preserved'
    for path in (ROOT / 'content/zh').rglob('*.md'):
        assert (ROOT / 'content/en' / path.relative_to(ROOT / 'content/zh')).exists(), f'Missing English counterpart for {path}'
    before = {p: hashlib.sha256(p.read_bytes()).hexdigest() for p in files}
    subprocess.run([sys.executable, str(ROOT / 'scripts/build.py')], check=True)
    assert all(hashlib.sha256(p.read_bytes()).hexdigest() == h for p, h in before.items()), 'Build is not deterministic'
    print(f'PASS: {len(docs)} HTML pages, {internal} local links, 14 projects, 5 research records, 21 artworks, bilingual routes, confidentiality checks, and deterministic build.')

if __name__ == '__main__':
    main()
